# Working with Numpy - for mathematical operations

[NUMPY BLOG](https://jalammar.github.io/visual-numpy/)

In [1]:
import numpy as np

In [4]:
# how to create an array
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

# shape - means dimension of the array
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


- (5,) and (5,1) are different shapes
- (5,) -> signifies linear array and elements can be referred by a[0],a[1]...
- (5,1) -> a 2-d array, elements can be referred by a[0][0],a[1][0]

In [7]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

#indexing starts from 0
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [14]:
# Create Zeros, Ones, Custom array
a = np.zeros((3,3))
print(a)

print(type(a))

b = np.ones((2,3))
print(b)

# array of some constants
c = np.full((3,2),5)
print(c)

# Identity Matrix - Size/Square Matrix
d = np.eye(4)
print(d)

#Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.7725448  0.81704569 0.04224189]
 [0.10828687 0.36870207 0.83684147]]


### Slicing

In [16]:
print(randomMatrix[:,1])
print(randomMatrix[:,2])

[0.81704569 0.36870207]
[0.04224189 0.83684147]


In [17]:
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.7725448  0.81704569 0.04224189]
 [0.10828687 1.         1.        ]]


In [19]:
# set some rows and columns with any values
z = np.zeros((3,3))
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


## Data types

In [20]:
print(z.dtype)

float64


In [21]:
# set some rows and columns with any values
z = np.zeros((3,3),dtype=np.int64)
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [22]:
print(z.dtype)

int64


## Mathematical Operations

In [24]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])


# Element wise addition
print(x+y)
print(np.add(x,y))

# Element wise subtraction
print(x-y)
print(np.subtract(x,y))

# Element type multiplication
print(x*y)
print(np.multiply(x,y))

# Element type division
print(x/y)
print(np.divide(x,y))

# Element wise square root
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [28]:
# Matrix Multiplications / Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [31]:
# Multiplication(dot product) of vectors (linear array) - Scalar

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

# element wise dot product
print(a.dot(b))

30


In [32]:
print(a)

[1 2 3 4]


In [33]:
print(sum(a))

10


In [34]:
print(x)

[[1 2]
 [3 4]]


In [38]:
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [37]:
# np.sum?

In [40]:
# STACKING of arrays

print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [41]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [43]:
a = np.stack((a,b),axis=0)

In [44]:
# RESHAPE a Numpy Array

print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [45]:
print(a.shape)

(2, 4)


In [46]:
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [47]:
print(a.reshape((8,1)))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [48]:
print(a.reshape((8,)))

[ 1  2  3  4  1  4  9 16]


In [49]:
print(a.reshape((4,2)))

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [50]:
print(a.reshape((2,4)))

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [51]:
# if we don't know the number of columns and just know that we need 4 rows then we can pass -1 as number of columns
# and it will automatically calculate number of columns needed
print(a.reshape((4,-1)))

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [53]:
print(a.reshape(-1,4))

[[ 1  2  3  4]
 [ 1  4  9 16]]


# Numpy Random Module
- rand: Random values in a given shape.
- randn: Return a sample(or samples) from the 'standard normal' distribution.
- randint: Return random integers from low(inclusive) to high(exclusive).
- random: Returns random floats in the half-opoen interval [0.0, 1.0]
- choice: Generates a random sample from a given 1-D array
- Shuffle: Shuffles the contents of a sequence

In [56]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [67]:
np.random.shuffle(a)
print(a)

[ 5  6 13  7 14  8 12  9 11 10]


In [68]:
a = np.random.rand(2,3)
print(a)

[[0.13320906 0.03013914 0.80173997]
 [0.64972446 0.81118469 0.09714518]]


In [69]:
# returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

[[ 0.92419169 -0.54199906 -0.40035541]
 [-0.71236061 -0.60037892  1.68264794]]


In [72]:
a = np.random.randint(5,10,3)
print(a)

# Randomly pick one element from an array
elem = np.random.choice([1,4,3,2,7,11])
print(elem)

[9 6 7]
3


In [ ]:
# PSEUDO RANDOM NUMBER GENERATOR
# If we want that our random values should be generated in same order then we set the seed value in the beginning
# np.random.seed(1)

# Some more Numpy Functions - Statistics
- min,max
- mean
- median
- average
- variance
- standard deviation

In [74]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))

# find min along some axis
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
1
[1 2 3 4]
[1 5]


In [76]:
# Mean, average all the elements
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[3. 4. 5. 6.]
[2.5 6.5]


In [77]:
# Median
c = np.array([1,5,4,3,0])
print(np.median(c))

3.0


In [80]:
# Average
# mean vs average
print(np.mean(c))

# average is weighted
w = np.array([1,2,3,4,4])
print(np.average(c,weights=w))

2.6
2.5


In [84]:
# Standard Deviation
# Variance = Standard deviation squared
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

# Inbuilt function
dev = np.std(c)
var = dev**2

print(var)
print(np.var(c))


1.8547236990991407
3.44
3.44


In [85]:
a = np.random.randint(0,15, size=(4,4))

In [98]:
print(a)
print(a[(a>=5) & (a<=10)])
print(a[np.where((a>=5)&(a<=10))])

[[14 13  2  4]
 [14  5  3  4]
 [ 3  3 12  5]
 [12 12  1  9]]
[5 5 9]
[5 5 9]


In [99]:
np.where?